title: "Anusha Jeyaseelan"
subtitle: "Technical Writer and Content Strategist | AWS | Developer Infrastructure"

url: "https://github.com/anushjeya/anusha-jeyaseelan"
baseurl: "/anusha-jeyaseelan"

# Collections
collections:
  posts:
    output: false
  portfolio:
    output: true
    permalink: /:collection/:name/

show_excerpts: false

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "aqua"

sass:
  sass_dir: assets/css
  style: compressed

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Author info
author:
  name: "Anusha Jeyaseelan"
  avatar: "/assets/images/profile.jpg"
  bio: "Technical Writer â€¢ Cloud & Developer Infrastructure"
  location: "San Francisco Bay Area"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anushajeyaseelan/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/anushajeyaseelan"
